title:             Docker Indo
email:             your-email@example.com
description:       Berbagi tutorial docker bahasa indonesia (Tidak hanya Docker)
author:            Docker Indo
baseurl:           "/"
url:               ""

# Social Profiles
twitter_username:  DockerIndo
github_username:   DockerIndo
facebook_username: DockerIndo

# Build settings
markdown:          kramdown
paginate:          4
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
